apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-local-pvc
spec:
  storageClassName: postgres-local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Mi
  